[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_vault = "HJEf7PBN6TkYQgZ1Zc3bucqiQx2Stu4EkR7CJTr4ftVb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/v99ribeiro/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
