[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_marketplace_core = "DfR9PhSBmkmAHtwRuru8BYsctjw5YhjPby9h6fdJZQDR"
[programs.devnet]
anchor_marketplace_core = "DfR9PhSBmkmAHtwRuru8BYsctjw5YhjPby9h6fdJZQDR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "../wallet/Turbin3-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[[test.validator.clone]]
address = "CoREENxT6tW1HoK8ypY1SxRMZTcVPm7R94rH4PZNhX7d"
